server:
  port: 8080
spring:
  application:
    name: api-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.babacar.app.dto
  data:
    mongodb:
      uri: mongodb://localhost:27017/aircrafts